/**
 * packages/tools/<slug>/ を走査して apps/web/src/generated/tools.ts を書き出す。
 *
 * Web版は必ずこの registry 経由でツールを読み込む。
 * こうしておくと 03-generate がディレクトリを1つ足すだけで新しいページが生える。
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  WEB_APP_DIR,
  TOOLS_SRC_DIR,
  listToolSlugs,
  loadLedger,
} from "@tf/shared/node";
import { assertSlug } from "@tf/shared";
import { info, warn } from "./lib/log.ts";

const STEP = "gen-registry";
const OUT_DIR = resolve(WEB_APP_DIR, "src", "generated");
const OUT_FILE = resolve(OUT_DIR, "tools.ts");

function identifier(slug: string): string {
  return slug.replace(/-/g, "_");
}

export function generateRegistrySource(): string {
  const ledger = new Map(loadLedger().map((e) => [e.slug, e]));
  const slugs = listToolSlugs().filter((slug) => {
    assertSlug(slug);
    const ui = resolve(TOOLS_SRC_DIR, slug, "web", "index.astro");
    if (!existsSync(ui)) {
      warn(STEP, `web/index.astro が無いので除外します: ${slug}`);
      return false;
    }
    return true;
  });

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/gen-registry.ts — 直接編集しないこと。",
    "// 再生成: pnpm gen",
    'import type { ToolMeta } from "@tf/shared";',
  ];

  for (const slug of slugs) {
    const id = identifier(slug);
    lines.push(
      `import { meta as meta_${id} } from "../../../../packages/tools/${slug}/meta.ts";`,
      `import Ui_${id} from "../../../../packages/tools/${slug}/web/index.astro";`,
    );
  }

  lines.push(
    "",
    "export interface ToolEntry {",
    "  meta: ToolMeta;",
    "  /** Astro コンポーネント（ツール本体のUI） */",
    "  Ui: unknown;",
    "  /** lifecycle が retired でない = 公開中 */",
    "  published: boolean;",
    "  /** sitemap の lastmod に使う ISO 日付 */",
    "  lastmod: string;",
    "}",
    "",
    "export const tools: ToolEntry[] = [",
  );

  for (const slug of slugs) {
    const id = identifier(slug);
    const entry = ledger.get(slug);
    const published = entry ? entry.lifecycle !== "retired" : true;
    const lastmod = entry?.web.deployed_at ?? entry?.created_at ?? null;
    lines.push(
      "  {",
      `    meta: meta_${id},`,
      `    Ui: Ui_${id},`,
      `    published: ${published},`,
      `    lastmod: ${lastmod ? JSON.stringify(lastmod) : `meta_${id}.createdAt`},`,
      "  },",
    );
  }

  lines.push("];", "");
  return lines.join("\n");
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  const source = generateRegistrySource();
  writeFileSync(OUT_FILE, source, "utf8");
  const count = (source.match(/^\s{4}meta: /gm) ?? []).length;
  info(STEP, `${count}件のツールを登録しました -> ${OUT_FILE}`);
}

main();
